-- Users table (stores profile settings)
create table if not exists users (
  id uuid default gen_random_uuid() primary key,
  username text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Contacts table
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null, -- For now we can assume a single user or link to auth.users if needed
  name text not null,
  relation text,
  email text,
  avatar text,
  is_primary boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Checkins table
create table if not exists checkins (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  type text check (type in ('safe', 'delayed', 'missed')) not null,
  date timestamp with time zone not null,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert a default user for testing if not exists
insert into users (username)
select '小雅'
where not exists (select 1 from users limit 1);
